name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
# -------------------------------------------------------------------------------------------------------------------------
# Event `push`: Compare the preceeding commit -> to the current commit of the main branch.
# Event `pull_request`: Compare the last commit of main -> to the current commit of a Pull Request branch.
# -------------------------------------------------------------------------------------------------------------------------

jobs:
  build:
    runs-on: ubuntu-latest  # windows-latest | macos-latest
    name: Test changed-files
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0  # OR "2" -> To retrieve the preceding commit.
      - name: Check for change in docs folder
        id: changed-documentation
        uses: tj-actions/changed-files@v35
        with:
          files: mono
      - name: 🔎 Check if files besides docs have changed
        id: changed-files
        uses: tj-actions/changed-files@v35
        with:
          files_ignore: mono
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: yarn
          cache-dependency-path: "**/package.json"
      - name: Install dependencies
        working-directory: ./mono
        run: yarn install
      - name: Test build website
        run: yarn build